name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  swift-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: swift build -c release --product progenyd
